### PR TITLE
fix(lib/v2): export es6 syntax free es modules

### PR DESCRIPTION
**Pull request by a20185**
remove `const` keyword from preventing compatibility issues

### CODE REVIEW

**Comment by a20185** [comment]
@antfu

**Comment by antfu** [comment]
I am ok with changes on cjs. But wondering in what kind of environment that you can use ES module `export` / `import` but does not support `const`?

**Comment by a20185** [comment]
We have a library that exports es modules(for convenience, name as pkgA), which uses vue-demi as dependency for develop cross-env plugins(e.g. `composables` that both supports Vue2&3).
 
As we deliver ESM that uses by user, the import and exports will be take care with user bundler. However, at common occasions, bundler treats the ESM in `node_module` as ES5+ESM, which means the `const` keyword syntax in node_modules's exports will not be defaultly transformed into the ES5 support version.(but import/export will be handled by the bundler)

This will be fixed by explicitly compiles all `node_modules` (which is the solution of some popular librarys, like `UmiJS` or   CRA, but will slowen the build speed or cause OOM problems), however in most occations the end user won't notice their transpiled-polyfilled-built results includes the env-unsupport syntaxs,  keywords, etc

**Comment by antfu** [comment]
Thanks for the explanation. `ES5+ESM` sounds a bit weird but it costs nothing to use `var` on my side anyway. Merged, thanks.

**Comment by antfu** [comment]
Released as v0.4.4

**Comment by a20185** [comment]
Got it, we need it a lot for our library.

IMO the weirdness probably because of the born of the ESM standard comes too late.

**Pull request merged**
